name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Website
        run: |
          sudo mkdir -p /var/www/html/simple-webpage
          sudo cp -r ./* /var/www/html/simple-webpage/
          sudo chown -R www-data:www-data /var/www/html/simple-webpage/
          sudo systemctl restart apache2
